# Generated by Django 2.0.1 on 2018-01-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=10)),
            ],
        ),
    ]
