# Generated by Django 2.0.1 on 2018-01-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20180117_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='grade',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.CharField(max_length=200),
        ),
    ]
