# Generated by Django 2.0.1 on 2018-01-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_auto_20180118_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='nations',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='premieres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='titles',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='nation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='premiere',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
