# Generated by Django 2.0.1 on 2018-01-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_sche', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgvschedule',
            name='no',
        ),
        migrations.RemoveField(
            model_name='ocnschedule',
            name='no',
        ),
        migrations.RemoveField(
            model_name='sactionschedule',
            name='no',
        ),
    ]
