# Generated by Django 2.0.1 on 2018-01-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_sche', '0002_auto_20180111_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultOcn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
